### PR TITLE
Rc responsive sign up

### PR DESCRIPTION
**Pull request by robert-czwartosz**
Hey, I've done responsive registration.

To test responsive sign up form run:
`npm run start:registrationTransition`

### CODE REVIEW

**Comment by skorpiom** [comment]
Hey, views looks really nice in mobile versions, but it seemes that there is a problem with the start page, because I fired it as you described - `start:registrationTransition` and main page looks like below

home_screen

**Comment by robert-czwartosz** [comment]
Thanks 👍 
Now it should looks good on every screen.

**Comment by skorpiom** [comment]
It looks good on every screen. 

Only problem is with that fruit picture, surprisingly it doesn't work for me if I run your unit implementation but it works if run:dev. Problem is that we shouldn't have white space in img name. But we can probably fix it later.

**Review by skorpiom — APPROVED** [review]

**Review by fszwedo — APPROVED** [review]
looks good for me as well :) thanks for adding the generics

**Pull request merged**
