### PR TITLE
Rc responsive menu

### PR DESCRIPTION
**Pull request by robert-czwartosz**
Responsive menu is done.

Please review my changes, test menu and report noticed bugs.

### CODE REVIEW

**Review by fszwedo — COMMENTED** [review]
not much to be suggested codewise,
I see that if you will go to the 'small screen' mode and hide the menu - then the menu stays hidden in "large screen" mode (but it's not a real-world situation so I'd leave it)

I also see that scrollbar is being applied for the dashboard elements, showing an unexpected white area (I was wondering for a few moments where did this thing came from :))
image

I think you can either make a separate rule for ```::-webkit-scrollbar``` for those elements to make its width 0px or disable overflow-y (not sure if it's acceptable)

I would resolve the abovementioned scroll issue as it might get the reviewers attention :)

**Comment by robert-czwartosz** [comment]
@fszwedo If you would resolve this problem, please do it :)

**Review by fszwedo — APPROVED** [review]

**Comment by robert-czwartosz** [comment]
Thanks 👍

**Comment by skorpiom** [comment]
Works nice!
if you have found time you could check how it looks with this burger icon:

https://www.flaticon.com/free-icon/menu_545705?term=menu&page=1&position=8&page=1&position=8&related_id=545705&origin=search

**Review by skorpiom — APPROVED** [review]

**Pull request merged**
