### PR TITLE
Rc store user after log in

### PR DESCRIPTION
**Pull request by robert-czwartosz**
Logged in user is stored in LS.
To test this functionality run:
`npm run start:login`

To log out user manualy in browser console run:
`localStorage.loggedInUserName = ''`

### CODE REVIEW

**Review by fszwedo — APPROVED** [review]
looks good to me

**Comment by fszwedo** [comment]
@robert-czwartosz one thing though - it seems there's no fallback value for optional key 'goals':
image

it has caused some issues for me during testing, I guess this case can happen for users

**Review by skorpiom — APPROVED** [review]

**Comment by skorpiom** [comment]
works well!

**Comment by robert-czwartosz** [comment]
> 
> 
> @robert-czwartosz one thing though - it seems there's no fallback value for optional key 'goals':
> image
> 
> it has caused some issues for me during testing, I guess this case can happen for users

I hope bug is fixed....

**Pull request merged**
