### PR TITLE
KR Gather all in one

### PR DESCRIPTION
**Pull request by kjreczek**
- uzupełniłem plik app.ts tak aby wszystko już wyświetlało się na stronie głównej i było połączone ze sobą;
- wprowadziłem kilka poprawek stylistycznych oraz poprawek w kodzie jak zauważyłem że pewne rzeczy nie działały;
- trochę musiałem przerobić widok overview bo nie działał dobrze i nie podczytywał się tak jak inne widoki;
- do tego brancha domergowałem branch Filipa _Fs exercises view_ aby dodać widok exercises do całości;

### CODE REVIEW

**Review by robert-czwartosz — APPROVED** [review]
Looks good!
There are 2 bugs... 
Firstly, overview does not appear, after log in.
Secondly, image in initial view does not load, probably because of wrong .png filename.
When filename don't include spaces, image displays correctly.

**Review by robert-czwartosz — COMMENTED** [review]
Log in button logic requires some changes.

**Comment by robert-czwartosz** [comment]
I'll fix bug with log in, because this was my component

**Comment by skorpiom** [comment]
Looks drop dead gorgeous!
yea I created that overview view in different way because there was some information related to gauges - that you need to add firstly a container to dom and later work with them but anyway there are some problems with My diary, I mean, the cancel button takes you from My Diary to Overview view and other thing - 'TODAY CALORIES' gauge doesn't update calories.

**Comment by robert-czwartosz** [comment]
Moving to overview is caused by refreshing after click Cancel button in Food or Exercises view

**Comment by robert-czwartosz** [comment]
So bug you decribed is in food and exercise components.
It's not issue with overview.

By the way I fixed log in :)

**Comment by kjreczek** [comment]
Fixed:
- cancel button taking you back to overview
- adding food didn't refresh the calories gauge

Let me know if I missed anything
@robert-czwartosz Thanks for those fixes as well :)

**Comment by robert-czwartosz** [comment]
All works good!
Only bug is in Exercise view.
I mean, cancel button refreshing page and taking user back to overview.

**Comment by skorpiom** [comment]
I've got problem during adding new meals for example in lunch, that list below duplicates: 

doesntclear


Other thing - in this view it would be useful if the we implemented scroll bar, because in some point view looks like this: 

food scroll

And the weird thing is in the exercises in` start:dev ` mode it's not possible to change dates, but in` start:views` it works.

**Comment by fszwedo** [comment]
FYI @robert-czwartosz @skorpiom @kjreczek the bug with exercises cancel refreshing the page has been fixed with the solution that Konrad prepared, it's on the branch exercisesview

**Comment by kjreczek** [comment]
@skorpiom Added scroll bar and fixed issue with duplicates and I have an idea why component with date in exercise doesn't work but first we must merge Filips pull because there will be some conflicts.

**Comment by kjreczek** [comment]
@skorpiom fixed everything that you mentioned, i hope it is good now

**Comment by skorpiom** [comment]
Right now it's almost perfect ;)
I found only one small thing, when you add meals, _today calories gauge_ doesn't update without refreshing page.
I think it would be enough if you just put this function **generateGaugesContent(user);** to ADD button function.

**Comment by kjreczek** [comment]
@skorpiom done 👍

**Comment by skorpiom** [comment]
Great! ;)

**Review by skorpiom — APPROVED** [review]

**Pull request merged**
