### PR TITLE
IP Views

### PR DESCRIPTION
**Pull request by skorpiom**
Hey,

That are views.
Please ignore SetRemainingCalories component files - I needed them before component was merged.

If you've got properly set test user you should be able to test views without any problems, but in case of problems I left in unit implementation / Views.ts commented user object you can easly put in LS. 

To start views:

`npm  run start:views`

### CODE REVIEW

**Review by fszwedo — APPROVED** [review]
all seems to be good, working fine for me :)

**Comment by fszwedo** [comment]
@skorpiom there are some conflicts, could you please take a look?

**Review by robert-czwartosz — APPROVED** [review]
Views look well!

**Comment by skorpiom** [comment]
I resolved conflicts but got some error

`Error: Path does not exist /home/runner/work/CodersCamp2020.Project.TypeScript.FitNotFat/CodersCamp2020.Project.TypeScript.FitNotFat/dist`

@fszwedo is it something related to gh workflow?

**Comment by fszwedo** [comment]
not really, there was a comma missing in package json - added it, should be ok now

**Pull request merged**
