### PR TITLE
Rc responsive dashboard

### PR DESCRIPTION
**Pull request by robert-czwartosz**

### CODE REVIEW

**Review by fszwedo — COMMENTED** [review]
looks awesome :) I would just change one thing - in overview there is a table which height could be increased (it's higher in desktop mode)
image

**Comment by robert-czwartosz** [comment]
Remaining calories should look well on every screen

**Review by fszwedo — APPROVED** [review]

**Comment by skorpiom** [comment]
Responsive designs works great!
the only problem is with desktop My Goals version
myGoals

**Comment by robert-czwartosz** [comment]
Thanks 👍  Fixed!

**Review by skorpiom — APPROVED** [review]

**Pull request merged**
